### ISSUE TITLE
Non-tweened keyframes

### ISSUE THREAD

**Issue by chrisbateman** [jeremyckahn/rekapi#35]
I'd like to add keyframes that snap directly to the values, rather than tweening to them.

So, currently, I'm writing code like this:
```
actor
    .keyframe(0, {x: 0})
    .wait(999)
    .keyframe(1000, {x: 100})
    .wait(1999)
    .keyframe(2000, {x: 200});
```

But it'd be great to do something like this:
```
actor
    .keyframe(0, {x: 0})
    .keyframe(1000, {x: 100}, 'snap')
    .keyframe(2000, {x: 200}, 'snap');
```

**Comment by jeremyckahn** [comment]
Hi @chrisbateman, thanks for your suggestion, but I don't think that this API would be a good fit for Rekapi.  Preventing a tween goes against what this library is about, but you're in luck: I recently added support for [function keyframes](http://rekapi.com/dist/doc/classes/Rekapi.Actor.html#method_keyframe), which allow you to execute arbitrary functions at specific points in the timeline.  With this approach, you could set the state on the actor that you want without tweening:

````javascript
actor
    .keyframe(0, function () {
      // Do something with {x: 0}
    })
    .keyframe(1000, function () {
      // Do something with {x: 100}
    })
    .keyframe(2000, function () {
      // Do something with {x: 200}
    });
````

It's not super elegant, but it should enable you to sequence states like you trying to do.  I hope this helps!

**Comment by chrisbateman** [comment]
Thanks for the quick response. Just looking for ways to better organize complex animations (which for me could include both tweened and immediate components).
