### ISSUE TITLE
Name option in toString sets selector for every actor to same thing

### ISSUE THREAD

**Issue by jeremiahmmv2** [jeremyckahn/rekapi#43]
I'll try to keep this short...

Imagine you have multiple Rekapi instances that are created on separate pages and the CSS is exported from both with `toString()`. They both have multiple actors with the name/class actor-1, actor-2, etc. Then say the CSS from both instances are needed on the same page. The `.actor-1` animations would clash.

As a solution, one might use the `name` option in `toString()`. But if I use `toString({name: 'test'})`, on a single stage with multiple actors, the CSS for ALL actors uses the `.test` selector.

As a workaround, I can add a single actor and generate the CSS with `toString({name: uniqueClassName})` and immediately remove the actor and simply do this for all the actors.

It would be nice if I could either A) set the class of an actor with a `setActorClassName()` method or a `prefix` or `parentId` option in `toString()`.

That way I could do something like this:
```javascript
var prefix = 'abc123-';
rekapi.renderer.toString({prefix: prefix});
```
And get a result like:
```css
/* Stage 1 */
.abc123-actor-1{
 ...
}
.abc123-actor-2{
 ...
}
/* Stage 2 */
.abc567-actor-1{
 ...
}
.abc567-actor-2{
 ...
}
```

Or:

```javascript
var parentId = 'abc123';
rekapi.renderer.toString({parentId: parentId});
```

And get a result like:
```css
/* Stage 1 */
#abc123 .actor-1{
 ...
}
#abc123 .actor-2{
 ...
}
/* Stage 2 */
#abc567 .actor-1{
 ...
}
#abc567 .actor-2{
 ...
}
```

Or just let me know if I'm missing something obvious...

**Comment by jeremyckahn** [comment]
Based on what you're describing, it seems that your namespacing logic could be achieved with just `toString`'s `name` parameter.  So, instead of 

````javascript
.toString({
  prefix: 'my-prefix`,
  name: 'my-name'
})
````

you could just have

**Comment by jeremiahmmv2** [comment]
I decided to use the catimate demo to show the problem I'm having with the name option. There may be something fundamental I'm not understanding. Here are the parts of catimate I altered:

```html
  <div id="actor-container">
    <img id="actor" src="img/octocat.png">
    <!-- Added second octocat -->
    <img id="actor2" src="img/octocat.png">
  </div>
```

```javascript
    require.config({
      paths: {
        shifty: "../dist/shifty.min",
        underscore: "../dist/lodash.min",
        rekapi: "../dist/rekapi"
      }
    });

    // Dependencies (Underscore and Shifty) are automatically loaded.
    require(['rekapi'], function(Rekapi) {
      var rekapi = new Rekapi(document.body)
          ,cat
          ,time = 0;

      //Actor 1
      var catImg = document.getElementById('actor');
      cat = new Rekapi.Actor({ context: catImg });
      rekapi.addActor(cat);

      cat
        .keyframe(time, {
          'transform': 'translate(-240px, -160px) rotate(0deg)'
        }).keyframe(time += 1200, {
          'transform': 'translate(300px, 250px) rotate(0deg)'
        }, 'bouncePast')
        .wait(time += 400)
        .keyframe(time += 700, {
          'transform': 'translate(50px, 250px) rotate(0deg)'
        }, 'easeInOutBack')
        .wait(time += 150)
        .keyframe(time += 850, {
          'transform': 'translate(344px, 0px) rotate(-90deg)'
        }, {
          'transform': 'easeFromTo easeInOutCubic bouncePast'
        })
        .keyframe(time += 700, {
          'transform': 'translate(344px, 800px) rotate(-90deg)'
        }, 'easeFrom')
        .wait(time += 500);

      catImg.style.display = 'block';

      //Actor 2
      var catImg2 = document.getElementById('actor2');
      cat = new Rekapi.Actor({ context: catImg2 });
      rekapi.addActor(cat);
     
      //Delay 1s
      time = 1000;

      cat
        .keyframe(time, {
          'transform': 'translate(-240px, -160px) rotate(0deg)'
        }).keyframe(time += 1200, {
          'transform': 'translate(300px, 250px) rotate(0deg)'
        }, 'bouncePast')
        .wait(time += 400)
        .keyframe(time += 700, {
          'transform': 'translate(50px, 250px) rotate(0deg)'
        }, 'easeInOutBack')
        .wait(time += 150)
        .keyframe(time += 850, {
          'transform': 'translate(344px, 0px) rotate(-90deg)'
        }, {
          'transform': 'easeFromTo easeInOutCubic bouncePast'
        })
        .keyframe(time += 700, {
          'transform': 'translate(344px, 800px) rotate(-90deg)'
        }, 'easeFrom')
        .wait(time += 500);

      catImg2.style.display = 'block';

      if (rekapi.renderer.canAnimateWithCSS()) {

        /**
          * Dump CSS to console
          */
        console.log(rekapi.renderer.toString({name: 'test'}));

        rekapi.renderer.play();
      } else {
        rekapi.play();
      }
    });
```

This is the part I don't quite understand. Both animations get the `.test` selector:

```css
.test {
  animation-name: test-transform-keyframes;
  animation-duration: 4500ms;
  animation-delay: 0ms;
  animation-fill-mode: forwards;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
}
@keyframes test-transform-keyframes {
...
}
.test {
  animation-name: test-transform-keyframes;
  animation-duration: 4500ms;
  animation-delay: 1000ms;
  animation-fill-mode: forwards;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
}
@keyframes test-transform-keyframes {
...
}
```
How come you can't make each animation's selector unique?

**Comment by jeremyckahn** [comment]
Ahh, I understand.  It looks like Rekapi isn't accounting for multiple actors in CSS animations.  Unless I forgot that I handled this (I wrote it a while ago), this might be a design oversight on my part.  Sorry about that!  A workaround would be to use a Rekapi instance for each actor, with each instance using a different `name` for the CSS string.

I'll need to dig into this further, but I probably won't have a substantive update until this weekend.  If you need something before then, feel free to submit a Pull Request.  The changes will need to take place in [`rekapi.renderer.dom.js`](https://github.com/jeremyckahn/rekapi/blob/master/renderers/dom/rekapi.renderer.dom.js).

**Comment by jeremiahmmv2** [comment]
Great! I can probably wait for an update. I'm just trying tease out any roadblocks before I start coding a CSS export option in a few days. I believe this was the last issue. 

Whoop! I just added rekapi to my ember-cli app. Onward and upward!

**Comment by jeremyckahn** [comment]
There was a bug!  I made a preliminary fix (referenced above).  Please pull down the [`bugfix/multiple-css-actors`](https://github.com/jeremyckahn/rekapi/tree/bugfix/multiple-css-actors) branch and test out my fix.  You will need to run `grunt build

**Comment by jeremyckahn** [comment]
I made a proper PR for reviewing and testing purposes: https://github.com/jeremyckahn/rekapi/pull/44

**Comment by jeremyckahn** [comment]
Released in [https://github.com/jeremyckahn/rekapi/releases/tag/1.6.2](https://github.com/jeremyckahn/rekapi/releases/tag/1.6.2).  Thanks again for reporting!
