### ISSUE TITLE
reset (or similar) function for actors

### ISSUE THREAD

**Issue by clemens** [jeremyckahn/rekapi#51]
Use case: I have an animation that acts as a guide to help the user correctly perform a physiotherapeutic exercise. The animation helps the user to stay in the correct timing (e.g. stretch for a certain amount of time, then release). In addition to the visual animation, audio cues (MP3s played via the HTML5 media API) are provided at certain keyframes (via keyframe functions).

The animation gets started when the user presses a button and then gets played the given number of times (each loop corresponding to one repetition) for the current set. The user can manually stop the animation (e.g. if repetitions are starting to get painful). And this is where problems arise.

Problem: When the user stops and then restarts the animation, audios that were already played aren't played again. The animation itself runs just fine, but audios only resume after the point where the user had pressed stop.

I've managed to track this down to the fact that function keyframes get a `hasFired` property which doesn't get reset when `stop` is called. Also, there doesn't seem to be a public function `reset` (or something similar) to reset an animation/individual actor into its original state so function keyframes would get reset to `hasFired = null`.

I've worked around it by using the following code (which I've copied from `Rekapi.prototype.playFrom`):

``` coffee
_.invoke(@animation._actors, '_resetFnKeyframesFromMillisecond', 0)
```

The code does its job but I don't like that I'm messing with Rekapi internals by calling two private functions.

Am I doing this wrong or am I just using function keyframes in a way that Rekapi didn't intend them to be used? If not: Would it make sense to somehow expose that functionality via the public API?

**Comment by jeremyckahn** [comment]
Hi @clemens, thank you for reporting this, and for the excellent writeup!  What you're working on sounds pretty cool.  I think your instincts are correct, it's best to avoid using internal methods — Rekapi should either expose this functionality publicly or obviate the need for it entirely.

I'm thinking that there should be a check in [`Rekapi.prototype.update`](https://github.com/jeremyckahn/rekapi/blob/6ebc158dd10165df3a839016105467841a9a672d/src/rekapi.core.js#L582) to see if `opt_millisecond` (the millisecond for which to render) is less than `this._lastUpdatedMillisecond`, and set `opt_doResetLaterFnKeyframes` to `true` if so.  I need to experiment with this a bit, but I don't have the time to do it right now.  I'll prioritize getting a fix out for this. I hope to have an update sometime this week!

**Comment by jeremyckahn** [comment]
I'm digging into this now — it looks like you might be able to achieve what you want with the existing APIs.  Calling `playFrom` resets the function keyframes, as you pointed out.  Could you use that method to restart playback?  Or have you tried that, and it doesn't work?

If that does work, I'm on the fence if additional logic should be added to address this.  On the one hand, having things "just work" is valuable.  On the other hand, this is the first time this has come up, so it feels like an edge case.  Performance is important in an animation library, so I'm cautious about adding more logic into a hot path.

Please let me know if `playFrom` does the trick, and any other thoughts you might have.

**Comment by jeremyckahn** [comment]
Actually, I think I might have a fix that shouldn't materially affect performance.  @clemens, could you please pull down my `feature/reset-fn-keyframes-on-play` branch, `grunt build` it, and test it?

**Comment by clemens** [comment]
I actually saw that `playFrom` does this (probably should have mentioned this in my original post). The irritating thing was the functional discrepancy between `play` and `playFrom`. As a user of the library, I'd expect `play` and `playFrom(0)` to be functionally equivalent.

The fix in the new branch seems to do the trick. Looking at the code, I think you could still improve it by removing the reset code from `playFrom` since this is now covered in `play` anyway, right? Other than that I'm looking forward to the next release so I can update. :) Thanks!

**Comment by jeremyckahn** [comment]
> Looking at the code, I think you could still improve it by removing the reset code from `playFrom` since this is now covered in play anyway, right?

I had considered that, but the issue with removing the "reset" code from `playFrom` is that all function keyframes will be reset, even ones earlier in the timeline.  This may have unintentional side effects.

And... as I was typing that out, I realized that I might be introducing that very bug because `playFrom` calls `play` and resets all the function keyframes from `0` anyways.  Whoops.  I'll double-back and fix that issue when I have a bit of time.  Thanks for pointing this out to me!

**Comment by clemens** [comment]
Here's a thought: Shouldn't the resetting be part of the `stop` function? If I `stop` the animation and then call `play` again, the animation (= non-function keyframes) runs from the start, so the function keyframes should be reset as well, right?

**Comment by jeremyckahn** [comment]
Yes, but that won't cover all use cases.  If the animation is already playing, and `playFrom(x)` is called (which is supported), then the relevant function keyframes won't be reset because `stop` was never called.

**Comment by clemens** [comment]
As you said, `playFrom(x)` is a specific use case. I guess the behavior should be as follows:

- `playFrom(x)`: reset all function keyframes >= x, then play from x
- `stop`: reset all function keyframes

In other words: `rekapi.stop(); rekapi.play()` should be functionally equivalent to `rekapi.playFrom(0)`.

**Comment by jeremyckahn** [comment]
I see now.  I like your approach; I'll give that a try when I get back into this.  Thanks for the insight!

**Comment by jeremyckahn** [comment]
@clemens, please review #53 when you get a chance.  Thanks!

**Comment by clemens** [comment]
Great, thanks! :)
