### ISSUE TITLE
There is no main property in package.json

### ISSUE THREAD

**Issue by lingxuan630** [jeremyckahn/rekapi#60]
Can not find main property in package.json! NPM can not resolve the `rekapi` module.

**Comment by jeremyckahn** [comment]
Oh no!  What a silly mistake.  Thanks for reporting this, I am fixing it right now!

**Comment by jeremyckahn** [comment]
This should be fixed in [v2.0.1](https://github.com/jeremyckahn/rekapi/releases/tag/v2.0.1)!

**Comment by jeremyckahn** [comment]
Note: I am now noticing that the module can't be loaded in Node environments without JSDOM.  This is a separate issue from the one you reported, and I will make a proper fix for it once I have some time to do so.
