### ISSUE TITLE
Custom easing function

### ISSUE THREAD

**Issue by serzhb** [jeremyckahn/rekapi#63]
Hello.
i'd like to add custom easing function for keyframe. I have a bezier curve look like "0.755, 0.050, 0.855, 0.060". Is it possible?

**Comment by jeremyckahn** [comment]
Hi @serzhb! Yes this is possible — you just need to use Shifty's [`setBezierFunction`](http://jeremyckahn.github.io/shifty/doc/shifty.html#.setBezierFunction) method. Shifty is the animation engine that powers Rekapi, and the latter inherits the easing functions from the former.  You should be able to achieve what you are looking for with something like:

```js
import { setBezierFunction } from 'shifty';

setBezierFunction('myCustomEasingFunction', 0.755, 0.050, 0.855, 0.060);
```

I don't love this current design, but it should at least solve your problem. 🙂
